#!/bin/sh

#Prepend the file with "#!/bin/sh"...use sh over bash in case of another implementation
echo \#\!/bin/sh\\n | cat - $1 > /tmp/out && mv /tmp/out $1

#Give the file executable permissions
chmod +x $1

# save /Env/scripts "adding $1 to the repo of blessed scripts"
