#!/bin/sh

share_path=$(secret global.share.remote.path)

username=$(secret global.share.username)

password=$(secret global.share.password)

share_mount_path=$(secret global.share.local.path)

# Check if share is already mounted
if [ ! -d $share_mount_path ]; then
	sudo mkdir $share_mount_path

	#mount the time capsule 
	sudo mount_afp afp://${username}:${password}@${share_path} $share_mount_path
fi

