#!/bin/sh

Default='\033[0m' # No Color
Black='\033[0;30m'     
DarkGray='\033[1;30m'
Red='\033[0;31m'     
LightRed='\033[1;31m'
Green='\033[0;32m'     
LightGreen='\033[1;32m'
Brown_Orange='\033[0;33m'     
Yellow='\033[1;33m'
Blue='\033[0;34m'     
Light_Blue='\033[1;34m'
Purple='\033[0;35m'     
Light_Purple='\033[1;35m'
Cyan='\033[0;36m'     
Light_Cyan='\033[1;36m'
Light_Gray='\033[0;37m'     
White='\033[1;37m'

function log_title()
{

}

function log_step()
{

}

function log_info()
{
	echo -e "${Yellow}Info: ${Default}$1"
}

function log_warning()
{
	echo -e "${Yellow}Warning: ${Default}$1"
}

function log_error()
{
	echo -e "${Red}Error: ${Default}$1"
}