#!/bin/sh

#######################################
#             Secrets                 #
#######################################

bin=$(secret global.bin.path)

scripts=$(secret global.scripts.path)

script_libs=$(secret global.script.lib.paths) 

bash_profile=$(secret global.bash.profile.path)

#######################################
#       Restore All The Things        #
#######################################

# Copy over all files from backup

# Copy over all executables that we expect to be in the path

# Put global bin first to give it precedence
echo "\nPATH=$bin:\$PATH\nexport PATH" >> $bash_profile

# Put scripts in path
echo "\nPATH=\$PATH:${scripts}\nexport PATH" >> $bash_profile

# Have all global script libs be available to all terminals and thus scripts
for lib in $script_libs
do
	echo "\nsource $lib" >> $bash_profile
done