#!/bin/sh

#Log a value or list of values based on a key in the /Env/.secrets.md

value_found=1
key=$1
values=''

while read line; do

	# Find the key
	if [[ $line == \#[[:space:]]$key ]] ; then

		while read line; do

			if  [[ $line == \-* ]] ; then

				if [ $value_found -eq 1 ] ; then
					values="$line"
					value_found=0
				else
					values="$values $line"
				fi
	
			else
				echo "${values//- }"
				exit $value_found
			fi

		done
	fi

done < /Env/.secrets.md